//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GisqLandPlanCmd.rc
//
#define IDS_PROJNAME                    100
#define IDR_GISQLANDPLANCMD             101
#define IDR_CLPXZQWINDOWCMD             103
#define IDD_LPXZQWINDOWDLG              104
#define IDR_LPGHJQDLTBCXCMD             105
#define IDR_LPGHDLTBCXCMD               106
#define IDR_LPGHQYTDKCXCMD              107
#define IDR_LPJSYDGZQCXCMD              108
#define IDR_LPGRIDDOCKWINCMD            109
#define IDR_LPGETXZQDATACMD             110
#define IDR_ILPXZQDATATREE              111
#define IDR_LPXZQDATATREE               112
#define IDR_LPXZQDATAENUM               113
#define IDR_LPXZQDATAITEM               114
#define IDR_LPATTRSEARCHCMD             115
#define IDR_LPGHGXCX                    116
#define IDR_LPGHGXCXCMD                 117
#define IDR_LPGHGXRSTCMD                119
#define IDR_LPREALTIMEUPDATECMD         120
#define IDR_IMPORTTODATABASE            121
#define IDR_ZOOMTOTOPXZQ                122
#define IDR_LPEXPORTDATACMD             123
#define IDR_LPSYSTEMSETCMD              124
#define IDC_TREE1                       201
#define IDC_XZQ_TREE                    201
#define IDB_BITMAP1                     201
#define IDB_DISTRICT_ICON_DOCKWND       201
#define IDC_COMBO1                      202
#define IDC_XZCOMBO                     202
#define IDC_TARGETTYPE                  202
#define IDC_COXTARGETTYPE               202
#define IDC_COMBO_CXLX                  202
#define IDC_EXPDATAXZQ_CBX              202
#define IDC_GXSJ_COMBO                  202
#define IDC_COMBO2                      203
#define IDC_CUNCOMBO                    203
#define IDC_CBX_XZQ                     203
#define IDC_COMBO_FAXMLX                203
#define IDC_COMBO3                      204
#define IDC_GHDLCOMBO3                  204
#define IDD_LPGHQYTDKCXDLG              204
#define IDC_CBX_DLMC                    204
#define IDC_COMBO_MJLX                  204
#define IDC_RADIO1                      205
#define IDC_METER_RD                    205
#define IDD_LPJSYDGZQCXDLG              205
#define IDC_UNIT_METER                  205
#define IDC_COMBO_ZBLX                  205
#define IDC_RADIO2                      206
#define IDC_MU_RD                       206
#define IDD_GRIDDOCKWIN                 206
#define IDC_UNIT_MU                     206
#define IDC_RADIO3                      207
#define IDC_HECTARE_RD                  207
#define IDC_UNIT_HECTARE                207
#define IDC_CXBUTTON                    208
#define IDD_GHJQDLTBCXDLG               209
#define IDD_LPGHJQDLTBCXDLG             209
#define IDC_TBMJMIN                     210
#define IDC_TBMJMAX                     211
#define IDC_UNITTEXT1                   212
#define IDC_UNITTEXT2                   213
#define IDC_TBDLMJMIN                   214
#define IDC_UNITTEXT3                   215
#define IDC_TBDLMJMAX                   216
#define IDC_UNITTEXT4                   217
#define IDB_BMP_ICON_SHENG              217
#define IDC_RESCOUNT                    218
#define IDB_BMP_ICON_SHI                218
#define IDC_GRIDAREA                    219
#define IDB_BMP_ICON_XIANGZHEN          219
#define IDC_UNITTEXT21                  220
#define IDB_BMP_ICON_XIANQU             220
#define IDC_UNITTEXT22                  221
#define IDC_XZCOMBO_2                   222
#define IDD_ATTRSEARCHDLG               222
#define IDD_LPATTRSEARCHDLG             222
#define IDC_CUNCOMBO_2                  223
#define IDD_GRIDDOCKTABWND              223
#define IDC_GHDLCOMBO_2                 224
#define IDC_METER_RD_2                  225
#define IDC_MU_RD_2                     226
#define IDB_BMP_ICON_CUN                226
#define IDC_HECTARE_RD_2                227
#define IDB_BITMAP2                     227
#define IDB_BMP_ICON_ZXQC               227
#define IDC_GRIDAREA_2                  228
#define IDD_GHGXCXDLG                   228
#define IDC_GHDLMAX_2                   229
#define IDC_GHDLJMIN_2                  230
#define IDC_GHDLMIN_2                   230
#define IDD_FADKTABWND                  230
#define IDC_RESCOUNT_2                  231
#define IDC_CXBUTTON_2                  232
#define IDB_ZOOMTOXZQ                   232
#define IDD_LPGHDLTBCXDLG               233
#define IDC_XZCOMBO_3                   234
#define IDD_LPEXPORTDATADLG             234
#define IDC_GHDLCOMBO_3                 235
#define IDD_SYSTEMSETDLG                235
#define IDC_METER_RD_3                  236
#define IDC_MU_RD_3                     237
#define IDC_HECTARE_RD_3                238
#define IDC_TDYTQMJMIN                  239
#define IDC_UNITTEXT31                  240
#define IDC_UNITTEXT32                  241
#define IDC_TDYTQMJMAX                  242
#define IDC_GRIDAREA_3                  243
#define IDC_RESCOUNT_3                  244
#define IDC_CXBUTTON_3                  245
#define IDC_RESCOUNT_4                  246
#define IDC_METER_RD_4                  247
#define IDC_MU_RD_4                     248
#define IDC_HECTARE_RD_4                249
#define IDC_GRIDAREA_4                  250
#define IDC_CXBUTTON_4                  251
#define IDC_UNITTEXT41                  252
#define IDC_UNITTEXT42                  253
#define IDC_GZQLXCOMBO                  254
#define IDC_RESULTTAB_RECT              261
#define IDC_EDITMINAREA                 262
#define IDC_EDITMAXAREA                 263
#define IDC_UNITTEXT                    264
#define IDC_AREANAME                    265
#define IDC_RESTEXT                     266
#define IDC_TAB1                        267
#define IDC_RESGRIDTAB                  267
#define IDC_GH_SEARCH                   269
#define IDC_DLLX_TEXT                   271
#define IDC_EDIT_MC_SLH                 272
#define IDC_STARTTIMECTRL               275
#define IDC_STOPTIMECTRL                276
#define IDC_STATIC_LX                   277
#define IDC_STATIC_MJ                   278
#define IDC_EDIT_MINAREA                279
#define IDC_EDIT_MAXAREA                280
#define IDC_EDIT_MINZB                  282
#define IDC_EDIT_MAXZB                  283
#define IDC_GHGXCX_XZQ                  285
#define IDC_FALIST                      289
#define IDC_EDIT1                       290
#define IDC_EDIT2                       291
#define IDC_ZBFW                        292
#define IDC_EXPDATA_TIMECTRL            294
#define IDC_SYSSET_TIME                 295
#define IDD_GHGXCXRSTDLG                1000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        236
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         296
#define _APS_NEXT_SYMED_VALUE           125
#endif
#endif
